
<html>
 <head> 
  <meta charset="utf-8"> 
  <meta name="viewport" content="width=device-width,initial-scale=1"> 
  <title>responsive layout</title> 
  <style>
            *{
              box-sizing:border-box;
            }
            #container{
              background-color:black;
            }
            .row{
              width:100%;
            }
            h1{
              Text-align:center ;
              color:white;
            }
            p{
              border:1px solid blach;
              Background-color:gray;
              width:90%;
              height:150px;
              Margin-right:auto;
              Margin-left:auto;
              Font-family:helvetica;
              color:white;
              Overflow:auto;
            }
          #indian{
    background-color: brown;
   Text-align:center;
}

#chinise{
    background-color: darkorchid;
    Text-align:center;
}

#maxican{
    background-color:green;
    Text-align:center;
}
           
            @media(max-width:767px){
              .col-sm-1,
              .col-sm-2, 
              .col-sm-3,
              .col-sm-4,
              .col-sm-5,
              .col-sm-6,
              .col-sm-7,
              .col-sm-8,
              .col-sm-9,
              .col-sm-10,
              .col-sm-11,
              .col-sm-12
           
              .col-sm-1{
                width:8.33%;
              }
              .col-sm-2{
                 width:16.66%;
              }
              .col-sm-3{
                 width:25%;
              }
              .col-sm-4{
                 width:33.33%;
              } 
              .col-sm-5{
                 width:41.66%;
              }
              .col-sm-6{
                 width:50%;
              }
              .col-sm-7{
                 width:58.33%;
              }
              .col-sm-8{
                 width:66.66%;
              }
              .col-sm-9{
                 width:75%;
              }
              .col-sm-10{
                 width:83.33%; 
              } 
              .col-sm-11{
                 width:91.66%;
              }
              .col-sm-12{
                 width:100%;
              }
             
           }
       @media (min-width: 992px) {
    .col-lg-1, .col-lg-2, .col-lg-3, .col-lg-4, .col-lg-5, .col-lg-6, .col-lg-7, .col-lg-8, .col-lg-9, .col-lg-10, .col-lg-11, .col-lg-12 {
      float: left;
      padding: 15px;
    }
    .col-lg-1 {
      width: 8.33%;
    }
    .col-lg-2 {
      width: 16.66%;
    }
    .col-lg-3 {
      width: 25%;
    }
    .col-lg-4 {
      width: 33.33%;
    }
    .col-lg-5 {
      width: 41.66%;
    }
    .col-lg-6 {
      width: 50%;
    }
    .col-lg-7 {
      width: 58.33%;
    }
    .col-lg-8 {
      width: 66.66%;
    }
    .col-lg-9 {
      width: 75%;
    }
    .col-lg-10 {
      width: 83.33%;
    }
    .col-lg-11 {
      width: 91.66%;
    }
   .col-lg-12 {
      width: 100%;
    }
  }
@media (min-width: 768px) and (max-width: 991px) {
    .col-md-1, .col-md-2, .col-md-3, .col-md-4, .col-md-5, .col-md-6, .col-md-7, .col-md-8, .col-md-9, .col-md-10, .col-md-11, .col-md-12 {
      float: left;
      padding: 15px;
    }
    .col-md-1 {
      width: 8.33%;
    }
    .col-md-2 {
      width: 16.66%;
   }
    .col-md-3 {
      width: 25%;
    }
    .col-md-4 {
      width: 33.33%;
    }
    .col-md-5 {
      width: 41.66%;
    }
    .col-md-6 {
      width: 50%;
    }
    .col-md-7 {
      width: 58.33%;
    }
    .col-md-8 {
      width: 66.66%;
    }
    .col-md-9 {
      width: 75%;
    }
    .col-md-10 {
      width: 83.33%;
    }
    .col-md-11 {
      width: 91.66%;
    }
    .col-md-12 {
      width: 100%;
    }
  }
            </style> 
 </head> 
 <body> 
  <div id="container"> 
   <h1>OUR MENU</h1> 
   <div class="row"> 
    <div class="col-sm-12 col-md-6 col-lg-4"> 
     <div id="indian">
       INDIAN 
     </div> 
     <p>INDIAN_Indian cuisine consists of a variety of regional and traditional cuisines native to the Indian subcontinent. Given the diversity in soil, climate, culture, ethnic groups, and occupations, these cuisines vary substantially and use locally available spices, herbs, vegetables, and fruits. Indian food is also heavily influenced by religion, in particular Hinduism, cultural choices and traditions.[1] The cuisine is also influenced by centuries of Islamic rule, particularly the Mughal rule. Samosas and pilafs are examples.</p> 
    </div> 
   </div> 
   <div class="col-sm-12 col-md-6 col-lg-4"> 
    <div id="chinise">
      CHINESE 
    </div> 
    <p>CHINESE_Chinese cuisine is an important part of Chinese culture, which includes cuisine originating from the diverse regions of China, as well as from Overseas Chinese who have settled in other parts of the world. Because of the Chinese diaspora and historical power of the country, Chinese cuisine has influenced many other cuisines in Asia, with modifications made to cater to local palates. Chinese food staples such as rice, soy sauce, noodles, tea, and tofu, and utensils such as chopsticks and the wok, can now be found worldwide.</p> 
   </div> 
   <div class="col-sm-12 col-md-6 col-lg-4"> 
    <div id="maxican">
      MEXICAN 
    </div> 
    <p>MAXICAN_Mexican cuisine began about 9,000 years ago, when agricultural communities such as the Maya formed, domesticating maize, creating the standard process of maize nixtamalization, and establishing their foodways. Successive waves of other Mesoamerican groups brought with them their own cooking methods. These included the Olmec, Teotihuacanos, Toltec, Huastec, Zapotec, Mixtec, Otomi, Purépecha, Totonac, Mazatec, Mazahua, and Nahua.</p> 
   </div> 
  </div> 
 </body>
</html>
